### ISSUE TITLE
Subtasks of #2458 (Implement allowances and sites pages UX/UI improvements)

### ISSUE THREAD

**Issue by fczuardi** [Falafel-Fellows/lightning-browser-extension#1]
- [x] on empty allowances pages, display link instead of empty bar
- [x] always display the settings new icon on the top-right corner of the connected site box
- [x] SitePreferences  modal has updated copy
- [x] add disconnect link to SitePreferences modal
- [x] change `active` badge to `budget` badge
- [x] weblist item on Publishers now shows all data + fixed spacing
- [ ]
